import type { JavaInterviewQuestion } from '../../shared/simulation/types';

export const JAVA_INTERVIEW_DATASET: readonly JavaInterviewQuestion[] = [
  {
    id: "Q01",
    interviewerQuestion: "Can you tell me about yourself?",
    category: "Introduction / Project",
    difficulty: "easy",
    expectedClassification: "behavioral",
    mockAnswer: "I have around 3 years of experience working primarily on Java backend development. My main experience has been with Java, Spring Boot, REST APIs, SQL databases, and microservices. In my recent projects I've worked on developing backend services, integrating APIs, handling database operations using Spring Data JPA, and writing unit tests using JUnit and Mockito. I've also worked with tools such as Git, Maven, Docker, and Kafka depending on the project requirements. I enjoy backend development particularly around designing reliable APIs and solving performance and integration issues.",
    keyPoints: ["3+ years Java backend", "Spring Boot and REST APIs", "SQL and microservices experience", "Spring Data JPA and testing", "Git, Maven, Docker, Kafka"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q02",
    interviewerQuestion: "Can you explain your current project?",
    category: "Introduction / Project",
    difficulty: "easy",
    expectedClassification: "project",
    mockAnswer: "In my current project, I'm mainly involved in developing backend services using Java and Spring Boot. We expose REST APIs that are consumed by frontend applications and other internal services. My responsibilities include implementing business logic, database integration using JPA, handling validations and exceptions, writing unit tests, and troubleshooting production issues. We follow a layered architecture with controller, service, and repository layers. For some asynchronous workflows we use messaging, and we use standard Git-based development and CI/CD practices.",
    keyPoints: ["Java and Spring Boot services", "REST APIs for clients", "Layered controller/service/repository", "JPA, validation, unit tests", "Messaging and CI/CD practices"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q03",
    interviewerQuestion: "What exactly is your role in the project?",
    category: "Introduction / Project",
    difficulty: "easy",
    expectedClassification: "project",
    mockAnswer: "My role is primarily backend development. I work on understanding requirements, designing and implementing APIs, writing service-layer logic, integrating with databases and external services, and creating unit tests. I also participate in code reviews and debugging issues across development and testing environments.",
    keyPoints: ["Backend development focus", "API design and implementation", "Service layer and integrations", "Unit tests and code reviews", "Debugging across environments"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q04",
    interviewerQuestion: "Tell me about a challenging issue you solved.",
    category: "Introduction / Project",
    difficulty: "easy",
    expectedClassification: "behavioral",
    mockAnswer: "One challenging issue was an API whose response time increased significantly as the amount of database data grew. I analyzed the API flow and found that the main bottleneck was an inefficient database query and unnecessary data being loaded. I optimized the query, reviewed the indexes, and changed the code so only the required fields were retrieved. After testing with a larger dataset, the response time improved considerably. The main lesson was to investigate the complete request path instead of assuming the problem was only in the Java code.",
    keyPoints: ["Slow API as data grew", "Inefficient query and over-fetching", "Query and index optimization", "Measured improvement on large data", "Investigate full request path"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q05",
    interviewerQuestion: "Why did you choose Java for backend development?",
    category: "Introduction / Project",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Java has a mature ecosystem, strong typing, good performance, automatic memory management, and a large enterprise ecosystem. With Spring Boot, it's also relatively straightforward to build production-ready REST services and microservices. In enterprise applications, the availability of libraries, monitoring tools, testing frameworks, and developer experience makes Java a practical choice.",
    keyPoints: ["Mature ecosystem and typing", "Performance and garbage collection", "Spring Boot for REST/microservices", "Rich libraries and tooling", "Strong enterprise adoption"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q06",
    interviewerQuestion: "What is Java?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Java is a statically typed, object-oriented programming language designed to be platform independent through the JVM. Java source code is compiled into bytecode, which is then executed by the Java Virtual Machine. I've mainly used Java for backend services, REST APIs, business logic, and database-driven applications.",
    keyPoints: ["Statically typed OOP language", "Platform independent via JVM", "Source to bytecode compilation", "Backend and REST use cases"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q07",
    interviewerQuestion: "What is the difference between JDK, JRE and JVM?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "JVM is responsible for executing Java bytecode. JRE provides the JVM along with the runtime libraries required to run Java applications. JDK contains the JRE plus development tools such as the Java compiler and debugging tools. So, developers generally use the JDK to build applications, while the JVM is the actual execution engine.",
    keyPoints: ["JVM executes bytecode", "JRE is JVM plus runtime libs", "JDK adds compiler and dev tools", "Developers use JDK to build"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q08",
    interviewerQuestion: "What are the main OOP concepts in Java?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "The four main concepts are encapsulation, inheritance, polymorphism, and abstraction. Encapsulation means keeping data and behavior together and controlling access. Inheritance allows one class to reuse behavior from another. Polymorphism allows the same interface or method contract to have different implementations. Abstraction focuses on exposing the required behavior while hiding implementation details.",
    keyPoints: ["Encapsulation controls access", "Inheritance reuses behavior", "Polymorphism varies implementations", "Abstraction hides details"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q09",
    interviewerQuestion: "What is the difference between an abstract class and an interface?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "An abstract class can contain both abstract and concrete methods and can maintain instance state. An interface primarily defines a contract, although modern Java interfaces can also contain default and static methods. A class can implement multiple interfaces but can extend only one class. I generally use interfaces when I want to define a capability or contract between components.",
    keyPoints: ["Abstract class can hold state", "Interface defines a contract", "Multiple interfaces, one superclass", "Interfaces for component contracts"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q10",
    interviewerQuestion: "What is method overloading?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Method overloading means having multiple methods with the same name but different parameter lists within the same class. The compiler determines which method to call based on the arguments. It is compile-time polymorphism.",
    keyPoints: ["Same name, different parameters", "Resolved at compile time", "Compile-time polymorphism"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q11",
    interviewerQuestion: "What is method overriding?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Method overriding occurs when a subclass provides its own implementation of a method defined in its parent class. The method signature needs to follow the parent contract, and runtime polymorphism determines which implementation is executed.",
    keyPoints: ["Subclass replaces parent method", "Must match parent signature", "Runtime polymorphism"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q12",
    interviewerQuestion: "What is the difference between == and equals()?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "For objects, == compares references, meaning whether two variables point to the same object. equals() is intended to compare logical equality, depending on how the class implements it. For example, two different String objects can contain the same text and equals() can return true even though == can return false.",
    keyPoints: ["== compares object references", "equals() compares logical value", "Strings can differ on ==", "equals() depends on implementation"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q13",
    interviewerQuestion: "Why is String immutable in Java?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "String immutability provides several benefits including security, thread safety, caching, and predictable behavior. Since a String cannot be changed after creation, it can safely be shared. It also allows Java to use the String pool efficiently.",
    keyPoints: ["Security and thread safety", "Safe sharing across code", "String pool efficiency", "Predictable behavior"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q14",
    interviewerQuestion: "What is the difference between String, StringBuilder and StringBuffer?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "String is immutable, so every modification can create a new object. StringBuilder is mutable and is generally preferred when performing repeated string modifications in a single-threaded context. StringBuffer is also mutable but its methods are synchronized, so it provides thread-safety with additional overhead.",
    keyPoints: ["String is immutable", "StringBuilder mutable, single-threaded", "StringBuffer synchronized", "Choose builder for frequent edits"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q15",
    interviewerQuestion: "What is exception handling in Java?",
    category: "Core Java",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Java provides try, catch, finally, throw, and throws for exception handling. I normally catch exceptions at a meaningful application boundary, log the required diagnostic information, and convert low-level exceptions into appropriate application-level errors. In Spring Boot REST services, I prefer centralized exception handling using mechanisms such as @ControllerAdvice.",
    keyPoints: ["try/catch/finally/throw/throws", "Catch at meaningful boundaries", "Log and map to app errors", "@ControllerAdvice in Spring Boot"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q16",
    interviewerQuestion: "What is the difference between ArrayList and LinkedList?",
    category: "Collections",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "ArrayList is backed by a dynamic array, so random access by index is efficient. LinkedList is based on linked nodes, so inserting or removing elements can be efficient when you already have the relevant position, but random access is slower. In most application code I use ArrayList unless there is a specific reason to choose LinkedList.",
    keyPoints: ["ArrayList uses dynamic array", "Fast random access in ArrayList", "LinkedList better for insert/remove", "ArrayList default choice"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q17",
    interviewerQuestion: "How does HashMap work internally?",
    category: "Collections",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "HashMap uses the key's hash code to determine a bucket. The key is then compared using equals() when necessary to find the correct entry. Modern Java implementations can use a tree structure inside a heavily-collided bucket to improve lookup performance. Correct implementations of hashCode() and equals() are important when using custom objects as keys.",
    keyPoints: ["Hash code selects bucket", "equals() finds correct entry", "Tree for collided buckets", "hashCode/equals for custom keys"],
    followUpQuestion: "What happens when two keys have the same hash?",
    followUpAnswer: "Both keys can end up in the same bucket. Java then uses equality checks to determine the correct key. Modern implementations can use a tree structure for heavily collided buckets, which helps maintain better lookup performance.",
    followUpKeyPoints: ["Same bucket for colliding keys", "equals() disambiguates keys", "Tree structure in heavy collisions", "Better lookup when bucket grows"],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q18",
    interviewerQuestion: "Can HashMap contain null keys?",
    category: "Collections",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Yes. HashMap allows one null key and multiple null values. However, whether null should actually be used depends on the application because it can make business logic less explicit.",
    keyPoints: ["One null key allowed", "Multiple null values allowed", "Null can obscure business logic"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q19",
    interviewerQuestion: "What is the difference between HashMap and ConcurrentHashMap?",
    category: "Collections",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "HashMap is not designed for concurrent modifications by multiple threads. ConcurrentHashMap is designed for concurrent access and provides thread-safe operations with better concurrency than synchronizing an entire map. In multi-threaded applications where multiple threads need to access and update a shared map, ConcurrentHashMap is generally more appropriate.",
    keyPoints: ["HashMap not thread-safe", "ConcurrentHashMap for concurrency", "Better than full map lock", "Use when threads share map"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q20",
    interviewerQuestion: "What is HashSet?",
    category: "Collections",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "HashSet is a collection that stores unique elements. Internally it is based on hashing, so the hashCode() and equals() contract is important. It is useful when the main requirement is uniqueness rather than maintaining insertion order.",
    keyPoints: ["Stores unique elements", "Hash-based internally", "Relies on hashCode/equals", "Unordered uniqueness"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q21",
    interviewerQuestion: "What are lambda expressions?",
    category: "Java 8+",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Lambda expressions provide a concise way of representing behavior or a function. They are commonly used with functional interfaces and Java streams. For example, instead of creating an anonymous class for a simple operation, a lambda can express the operation directly.",
    keyPoints: ["Concise function syntax", "Used with functional interfaces", "Common with streams", "Replaces verbose anonymous classes"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q22",
    interviewerQuestion: "What is a functional interface?",
    category: "Java 8+",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "A functional interface has exactly one abstract method. It can be used as the target type of a lambda expression. Common examples include Predicate, Function, Consumer, and Supplier.",
    keyPoints: ["Single abstract method", "Target type for lambdas", "Examples: Predicate, Function"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q23",
    interviewerQuestion: "What are Java Streams?",
    category: "Java 8+",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Streams provide a declarative way to process collections and other data sources. Operations such as filter, map, sorted, and collect can be chained together. Streams are useful for readable transformations, although I avoid using overly complicated stream chains when a normal loop would be easier to maintain.",
    keyPoints: ["Declarative collection processing", "filter, map, sorted, collect", "Readable transformations", "Avoid overly complex chains"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q24",
    interviewerQuestion: "What is the difference between map and flatMap?",
    category: "Java 8+",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "map transforms each element into another element, while flatMap is used when each element can produce multiple elements and we want to flatten those results into a single stream. For example, if we have a list of customers and each customer has a list of orders, flatMap can be used to create one stream of orders.",
    keyPoints: ["map one-to-one transform", "flatMap flattens nested streams", "Example: customers to orders"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q25",
    interviewerQuestion: "What is Optional in Java?",
    category: "Java 8+",
    difficulty: "easy",
    expectedClassification: "technical",
    mockAnswer: "Optional is a container that represents either a value or no value. It can make absence explicit and reduce some forms of null handling. I mainly use it at appropriate API boundaries and repository return types rather than using Optional everywhere.",
    keyPoints: ["Represents value or empty", "Explicit absence vs null", "Use at API boundaries", "Not for every field"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q26",
    interviewerQuestion: "What is Spring Boot?",
    category: "Spring / Spring Boot",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "Spring Boot simplifies development of Spring applications by providing auto-configuration, starter dependencies, embedded servers, and production-oriented features. Instead of configuring everything manually, we can create a Spring Boot application with the required starters and focus more on business logic.",
    keyPoints: ["Auto-configuration", "Starter dependencies", "Embedded servers", "Focus on business logic"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q27",
    interviewerQuestion: "What is dependency injection?",
    category: "Spring / Spring Boot",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "Dependency injection means that a class receives the dependencies it needs from an external component instead of creating those dependencies itself. In Spring, the container manages these objects and injects them where required. I generally prefer constructor injection because dependencies are explicit and the class is easier to test.",
    keyPoints: ["Dependencies provided externally", "Spring container manages beans", "Avoids self-construction", "Constructor injection preferred"],
    followUpQuestion: "Why do you prefer constructor injection?",
    followUpAnswer: "Constructor injection makes required dependencies explicit and also makes the object easier to test because dependencies can be passed directly into the constructor. It also helps prevent partially initialized objects.",
    followUpKeyPoints: ["Dependencies explicit in constructor", "Easier unit testing", "Avoids partially initialized objects", "Required deps clear at compile time"],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q28",
    interviewerQuestion: "What is the difference between @Component, @Service and @Repository?",
    category: "Spring / Spring Boot",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "All three are Spring stereotypes used for component scanning, but they communicate different responsibilities. Component is generic, Service represents business logic, and Repository represents data-access logic. Using the appropriate annotation improves readability and allows Spring to manage these classes as beans.",
    keyPoints: ["All are Spring stereotypes", "Service for business logic", "Repository for data access", "Improves readability"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q29",
    interviewerQuestion: "What is @Autowired?",
    category: "Spring / Spring Boot",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "@Autowired tells Spring to inject a matching dependency. In newer Spring applications I generally prefer constructor injection, where Spring automatically resolves the constructor dependency, because it makes dependencies explicit and improves testability.",
    keyPoints: ["Spring resolves dependency", "Prefer constructor injection", "Explicit dependencies", "Better testability"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q30",
    interviewerQuestion: "What is Spring MVC?",
    category: "Spring / Spring Boot",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "Spring MVC is a web framework within Spring used to build web applications and REST APIs. A request is routed to a controller, the controller delegates business logic to services, and the response is returned to the client. Spring handles request mapping, validation, serialization, and many other web concerns.",
    keyPoints: ["Web framework in Spring", "Controller to service flow", "REST and web apps", "Mapping and serialization handled"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q31",
    interviewerQuestion: "What is @RestController?",
    category: "Spring / Spring Boot",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "@RestController is a convenience annotation that combines @Controller and @ResponseBody. It is commonly used for REST APIs because return values are automatically written to the HTTP response body and serialized, usually as JSON.",
    keyPoints: ["Combines @Controller and @ResponseBody", "Return values go to response body", "Typical for REST APIs", "JSON serialization"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q32",
    interviewerQuestion: "How do you handle exceptions globally in Spring Boot?",
    category: "Spring / Spring Boot",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "I generally use @ControllerAdvice with @ExceptionHandler methods. This allows us to centralize exception handling and return consistent HTTP responses. For example, validation errors can return a structured 400 response, resource-not-found errors can return 404, and unexpected errors can return a controlled 500 response without exposing internal details.",
    keyPoints: ["@ControllerAdvice central handler", "@ExceptionHandler per exception", "Consistent HTTP responses", "Hide internal error details"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q33",
    interviewerQuestion: "How do you validate REST API requests?",
    category: "Spring / Spring Boot",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "I commonly use Jakarta Bean Validation annotations such as @NotNull, @NotBlank, @Size, and @Email along with @Valid or @Validated. Validation errors can then be handled centrally through @ControllerAdvice to provide a consistent response structure.",
    keyPoints: ["Bean Validation annotations", "@Valid or @Validated on input", "Centralized error handling", "Consistent 400 responses"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q34",
    interviewerQuestion: "What is JPA?",
    category: "JPA / Hibernate / Database",
    difficulty: "medium",
    expectedClassification: "database",
    mockAnswer: "JPA is a Java specification for object-relational mapping. It defines how Java objects can be mapped to relational database tables. Hibernate is one of the most commonly used implementations of JPA.",
    keyPoints: ["ORM specification", "Maps objects to tables", "Hibernate implements JPA"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q35",
    interviewerQuestion: "What is Hibernate?",
    category: "JPA / Hibernate / Database",
    difficulty: "medium",
    expectedClassification: "database",
    mockAnswer: "Hibernate is an ORM framework that implements JPA and handles mapping between Java objects and relational database records. It can reduce boilerplate JDBC code and provides features such as entity mapping, persistence context, caching, and query support.",
    keyPoints: ["JPA implementation", "Object-relational mapping", "Less JDBC boilerplate", "Persistence context and caching"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q36",
    interviewerQuestion: "What is lazy loading?",
    category: "JPA / Hibernate / Database",
    difficulty: "medium",
    expectedClassification: "database",
    mockAnswer: "Lazy loading means related data is loaded only when it is actually accessed. It can reduce unnecessary database queries, but it needs to be handled carefully because accessing lazy relationships outside the persistence context can cause LazyInitializationException.",
    keyPoints: ["Loads relations on access", "Reduces upfront queries", "LazyInitializationException risk", "Needs open persistence context"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q37",
    interviewerQuestion: "What is the N+1 query problem?",
    category: "JPA / Hibernate / Database",
    difficulty: "medium",
    expectedClassification: "database",
    mockAnswer: "The N+1 problem happens when one query retrieves a list of entities and then an additional query is executed for each entity to retrieve related data. This can create a large number of database calls. Depending on the use case, we can address it with fetch joins, entity graphs, batch fetching, or carefully designed queries.",
    keyPoints: ["One query plus N per row", "Many round trips to DB", "Fetch joins or entity graphs", "Batch fetching or tuned queries"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q38",
    interviewerQuestion: "What is a database index?",
    category: "JPA / Hibernate / Database",
    difficulty: "medium",
    expectedClassification: "database",
    mockAnswer: "An index is a data structure that helps the database locate rows more efficiently for certain queries. It can significantly improve read performance but also adds storage and write overhead. I would create indexes based on actual query patterns rather than indexing every column.",
    keyPoints: ["Speeds targeted lookups", "Tradeoff on writes and storage", "Index by query patterns", "Avoid indexing everything"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q39",
    interviewerQuestion: "What is the difference between INNER JOIN and LEFT JOIN?",
    category: "JPA / Hibernate / Database",
    difficulty: "medium",
    expectedClassification: "database",
    mockAnswer: "INNER JOIN returns rows where matching records exist in both tables. LEFT JOIN returns all rows from the left table and matching rows from the right table, with nulls when there is no match.",
    keyPoints: ["INNER JOIN requires match both sides", "LEFT JOIN keeps all left rows", "Nulls when no right match"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q40",
    interviewerQuestion: "What makes an API RESTful?",
    category: "REST API",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "A RESTful API generally uses HTTP methods and resource-oriented URLs, remains stateless between requests, and uses standard HTTP status codes. For example, GET can retrieve a resource, POST can create one, PUT can update it, and DELETE can remove it.",
    keyPoints: ["HTTP methods on resources", "Stateless requests", "Standard status codes", "GET POST PUT DELETE semantics"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q41",
    interviewerQuestion: "What is the difference between PUT and PATCH?",
    category: "REST API",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "PUT is generally used to replace or fully update a resource, while PATCH is intended for partial updates. For example, if we only want to change a customer's phone number, PATCH is a natural choice.",
    keyPoints: ["PUT full replace/update", "PATCH partial update", "PATCH for single field change"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q42",
    interviewerQuestion: "What HTTP status codes do you commonly use?",
    category: "REST API",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "200 is commonly used for successful requests, 201 for successful creation, 204 when there is no response body, 400 for invalid requests, 401 for missing or invalid authentication, 403 for insufficient permissions, 404 when a resource isn't found, and 500 for unexpected server-side errors.",
    keyPoints: ["200 success, 201 created", "204 no content", "400 bad request", "401/403 auth issues", "404 not found, 500 server error"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q43",
    interviewerQuestion: "How would you secure a REST API?",
    category: "REST API",
    difficulty: "medium",
    expectedClassification: "backend",
    mockAnswer: "I would typically use HTTPS, authentication such as OAuth2 or JWT depending on the architecture, authorization based on roles or permissions, request validation, secure credential storage, appropriate CORS configuration, rate limiting where required, and centralized logging and monitoring. I would also avoid returning sensitive information in API responses or logs.",
    keyPoints: ["HTTPS and auth (JWT/OAuth2)", "Role-based authorization", "Validation and secret storage", "CORS and rate limiting", "Logging without sensitive data"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q44",
    interviewerQuestion: "What is a microservice?",
    category: "Microservices",
    difficulty: "medium",
    expectedClassification: "architecture",
    mockAnswer: "A microservice is a relatively small independently deployable service focused on a specific business capability. Services communicate through APIs or messaging. The main benefits can include independent deployment and scaling, but microservices also introduce complexity around distributed systems, monitoring, networking, and data consistency.",
    keyPoints: ["Small focused services", "Independent deployment", "API or messaging communication", "Distributed complexity tradeoffs"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "detailed",
  },
  {
    id: "Q45",
    interviewerQuestion: "What is the difference between monolith and microservices?",
    category: "Microservices",
    difficulty: "medium",
    expectedClassification: "architecture",
    mockAnswer: "A monolith packages multiple application capabilities into one deployable unit, while microservices split capabilities into independently deployable services. Microservices can provide independent scaling and deployment, but they introduce additional operational and distributed-system complexity. I wouldn't choose microservices automatically; the architecture should match the actual requirements.",
    keyPoints: ["Monolith single deployable unit", "Microservices split by capability", "Independent scale and deploy", "Choose based on requirements"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "detailed",
  },
  {
    id: "Q46",
    interviewerQuestion: "How do microservices communicate with each other?",
    category: "Microservices",
    difficulty: "medium",
    expectedClassification: "architecture",
    mockAnswer: "They can communicate synchronously using HTTP or REST APIs, or asynchronously using messaging systems such as Kafka. Synchronous communication is straightforward but creates runtime dependencies between services. Messaging can provide decoupling and better resilience for asynchronous workflows.",
    keyPoints: ["Sync HTTP/REST calls", "Async messaging like Kafka", "Sync creates runtime coupling", "Messaging decouples workflows"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "detailed",
  },
  {
    id: "Q47",
    interviewerQuestion: "What is Kafka?",
    category: "Microservices",
    difficulty: "medium",
    expectedClassification: "architecture",
    mockAnswer: "Kafka is a distributed event-streaming platform. Producers publish messages to topics, and consumers read those messages. Topics are divided into partitions, which provide scalability and parallelism. Kafka is useful for event-driven architectures, asynchronous processing, and integrating services without tightly coupling them.",
    keyPoints: ["Distributed event streaming", "Producers, topics, consumers", "Partitions for scale", "Event-driven integration"],
    followUpQuestion: "What happens if a consumer fails?",
    followUpAnswer: "Kafka keeps messages according to the topic's retention configuration. Consumers track their offsets, so a consumer can restart and continue from the appropriate offset. Depending on the consumer configuration and processing model, we can also implement retries and dead-letter handling.",
    followUpKeyPoints: ["Messages retained per topic policy", "Offsets track read progress", "Consumer can restart from offset", "Retries and dead-letter options"],
    expectedAnswerStyle: "detailed",
  },
  {
    id: "Q48",
    interviewerQuestion: "What is multithreading?",
    category: "Concurrency",
    difficulty: "hard",
    expectedClassification: "technical",
    mockAnswer: "Multithreading allows multiple threads to execute work concurrently within a process. It can improve throughput for suitable workloads, especially when tasks involve waiting or can be processed independently. However, shared mutable state needs careful synchronization.",
    keyPoints: ["Multiple threads per process", "Better throughput for IO/wait", "Shared state needs sync"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q49",
    interviewerQuestion: "What is the difference between synchronized and volatile?",
    category: "Concurrency",
    difficulty: "hard",
    expectedClassification: "technical",
    mockAnswer: "volatile primarily guarantees visibility of changes between threads for a variable, but it doesn't make compound operations atomic. synchronized provides mutual exclusion and visibility around a critical section. So if multiple operations need to happen atomically, synchronization or another concurrency mechanism is usually required.",
    keyPoints: ["volatile ensures visibility", "Not atomic for compound ops", "synchronized mutual exclusion", "Use sync for atomic blocks"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q50",
    interviewerQuestion: "What is ExecutorService?",
    category: "Concurrency",
    difficulty: "hard",
    expectedClassification: "technical",
    mockAnswer: "ExecutorService provides a framework for managing and executing asynchronous tasks using thread pools. Instead of manually creating threads for every task, we can submit tasks to an executor and let it manage the worker threads. It also provides lifecycle management and Future-based result handling.",
    keyPoints: ["Thread pool task execution", "Avoid manual thread per task", "Lifecycle management", "Future results"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q51",
    interviewerQuestion: "How do you write unit tests in Java?",
    category: "Testing",
    difficulty: "hard",
    expectedClassification: "technical",
    mockAnswer: "I commonly use JUnit for the test framework and Mockito for mocking dependencies. I focus on testing one unit of behavior at a time, arrange the required inputs and mocks, execute the method, and verify the expected result and important interactions. I also include negative and edge cases rather than testing only the happy path.",
    keyPoints: ["JUnit plus Mockito", "Arrange-act-assert flow", "One behavior per test", "Cover edge and negative cases"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q52",
    interviewerQuestion: "What is Mockito?",
    category: "Testing",
    difficulty: "hard",
    expectedClassification: "technical",
    mockAnswer: "Mockito is a mocking framework commonly used with Java unit tests. It allows us to create mock dependencies and define their behavior so that the class under test can be tested independently from external systems such as databases or APIs.",
    keyPoints: ["Mocking framework for tests", "Stub external dependencies", "Isolate class under test"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q53",
    interviewerQuestion: "What is Docker?",
    category: "Docker / Cloud",
    difficulty: "hard",
    expectedClassification: "devops",
    mockAnswer: "Docker packages an application and its dependencies into a container image so it can run consistently across environments. For Java applications, we can build the application, package it into a container image with the required JRE, and deploy that image to a container platform.",
    keyPoints: ["Container image packaging", "Consistent across environments", "JRE in image for Java apps", "Deploy to container platform"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q54",
    interviewerQuestion: "How would you deploy a Spring Boot application?",
    category: "Docker / Cloud",
    difficulty: "hard",
    expectedClassification: "cloud",
    mockAnswer: "I would first package the application using Maven or Gradle, run the automated tests, build the deployment artifact or Docker image, and then deploy it to the target environment. In a cloud environment this could be a container platform such as ECS or Kubernetes. I would also configure environment-specific settings, secrets management, health checks, logging, monitoring, and CI/CD.",
    keyPoints: ["Build with Maven or Gradle", "Tests then artifact or image", "Deploy to ECS/Kubernetes", "Secrets, health checks, CI/CD"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q55",
    interviewerQuestion: "Your API suddenly becomes slow in production. How would you investigate?",
    category: "Scenario Questions",
    difficulty: "hard",
    expectedClassification: "system_design",
    mockAnswer: "I'd first determine whether the issue is isolated to one endpoint or affects the entire service. I'd check application metrics, logs, latency, CPU and memory, database performance, and downstream dependencies. If the database is involved, I'd inspect slow queries and execution plans. I'd also compare the current deployment with the previous version. The goal would be to identify the bottleneck using evidence rather than immediately changing code.",
    keyPoints: ["Scope one endpoint vs all", "Metrics, logs, CPU/memory", "Database slow queries", "Compare deployments", "Evidence before code changes"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q56",
    interviewerQuestion: "An API is returning 500 errors intermittently. What would you do?",
    category: "Scenario Questions",
    difficulty: "hard",
    expectedClassification: "backend",
    mockAnswer: "I'd correlate the failed requests using logs and request IDs, identify whether the errors come from the application, database, or downstream service, and check the exception stack traces and surrounding metrics. If it's intermittent, I'd also look for concurrency issues, connection pool exhaustion, timeouts, or dependency failures. After identifying the root cause, I'd reproduce it if possible and add appropriate tests.",
    keyPoints: ["Correlate logs and request IDs", "Isolate app vs DB vs downstream", "Check pools, timeouts, concurrency", "Reproduce and add tests"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q57",
    interviewerQuestion: "How would you design a scalable REST API?",
    category: "Scenario Questions",
    difficulty: "hard",
    expectedClassification: "architecture",
    mockAnswer: "I'd keep the application stateless so multiple instances can serve requests behind a load balancer. I'd optimize database access, use appropriate indexes and connection pooling, introduce caching where useful, and move long-running work to asynchronous processing where appropriate. I'd also add monitoring, health checks, centralized logging, rate limiting, and automated deployment.",
    keyPoints: ["Stateless behind load balancer", "DB indexes and pooling", "Caching and async work", "Monitoring and rate limits"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "detailed",
  },
  {
    id: "Q58",
    interviewerQuestion: "How would you handle a database connection failure?",
    category: "Scenario Questions",
    difficulty: "hard",
    expectedClassification: "database",
    mockAnswer: "I'd first determine whether the failure is temporary or persistent. For transient failures, carefully configured retries with backoff may help, but retries shouldn't make an existing outage worse. I'd also use connection pool limits and timeouts so resources aren't exhausted. The application should return an appropriate error rather than exposing database details.",
    keyPoints: ["Transient vs persistent failure", "Retries with backoff carefully", "Pool limits and timeouts", "Safe error responses"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q59",
    interviewerQuestion: "How would you improve the performance of a Spring Boot application?",
    category: "Scenario Questions",
    difficulty: "hard",
    expectedClassification: "backend",
    mockAnswer: "I'd start by measuring the actual bottleneck. Depending on the results, improvements could include optimizing database queries and indexes, reducing unnecessary object creation, caching frequently accessed data, improving connection pool configuration, reducing unnecessary network calls, and tuning JVM settings where appropriate. I would validate every optimization using metrics rather than assuming it helped.",
    keyPoints: ["Measure bottleneck first", "Query and index tuning", "Caching and pool config", "Validate with metrics"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
  {
    id: "Q60",
    interviewerQuestion: "Why should we hire you for this Java role?",
    category: "Scenario Questions",
    difficulty: "hard",
    expectedClassification: "behavioral",
    mockAnswer: "I bring practical backend experience with Java and Spring Boot and I'm comfortable working across APIs, business logic, databases, testing, and integrations. I also have experience debugging issues rather than only implementing new features. At around three years of experience, I'm looking to continue taking ownership of backend components and grow further in system design and distributed systems.",
    keyPoints: ["Java and Spring Boot practice", "APIs through integrations", "Debugging production issues", "Growth in system design"],
    followUpQuestion: null,
    followUpAnswer: null,
    followUpKeyPoints: [],
    expectedAnswerStyle: "normal",
  },
];

export function getJavaInterviewDataset(): readonly JavaInterviewQuestion[] {
  return JAVA_INTERVIEW_DATASET;
}
